const robot=[
    {
        id:1,
        name:'suprava koley',
        username:'tanu',
        email:'su@dfh.com'
    },
    {
        id:2,
        name:'ri',
        username:'ri',
        email:'ri@r.com'
    },
    {
        id:3,
        name:'rihan',
        username:'tanu',
        email:'su@dfh.com'
    },
    {
        id:4,
        name:'chandu',
        username:'tanu',
        email:'su@dfh.com'
    },
    {
        id:5,
        name:'sam',
        username:'tanu',
        email:'su@dfh.com'
    },
    {
        id:6,
        name:'xyz',
        username:'tanu',
        email:'su@dfh.com'
    },
    {
        id:7,
        name:'ghffh',
        username:'tanu',
        email:'su@dfh.com'
    },
    {
        id:8,
        name:'yyyy',
        username:'tanu',
        email:'su@dfh.com'
    }
]
export default robot;